import React, { useState, useCallback, useEffect, useRef } from 'react';
import { Button } from 'antd';
import { CloseOutlined } from '@ant-design/icons';
import FilterRow from './FilterRow';
import './FilterBar.css';

// Filter types supported
export type FilterType = 'date' | 'amount' | 'entity' | 'category';

// Value types for different filters
export interface DateFilterValue {
    dateStart?: string;
    dateEnd?: string;
}

export interface AmountFilterValue {
    min?: number;
    max?: number;
}

export interface CategoryFilterValue {
    level1?: string;
    level2?: string[];
}

export type FilterValue = DateFilterValue | AmountFilterValue | CategoryFilterValue | string | string[] | number | null;

// State for a single filter row
export interface FilterRowState {
    id: string;
    type: FilterType | null;
    value: FilterValue;
    isAiGenerated?: boolean;  // Whether this row was generated by AI
}

// External filters interface (from SearchFilters)
export interface ExternalFilters {
    dateStart?: string;
    dateEnd?: string;
    amountMin?: number;
    amountMax?: number;
    ourEntity?: string | null;
    customerCategoryLevel1?: string[];
    customerCategoryLevel2?: string[];
}

// Props for FilterBar component
interface FilterBarProps {
    categoryHierarchy: Record<string, string[]>;
    entityOptions: string[];
    onFiltersChange: (filters: ExternalFilters) => void;
    externalFilters?: ExternalFilters;  // External filters to inject (e.g., from AI Smart Search)
}

// Generate unique ID
const generateId = (): string => {
    return `filter-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
};

// Convert ExternalFilters to FilterRowState array (for AI-generated filters)
export const convertExternalFiltersToRows = (filters: ExternalFilters): FilterRowState[] => {
    const rows: FilterRowState[] = [];

    // Date filter
    if (filters.dateStart || filters.dateEnd) {
        rows.push({
            id: generateId(),
            type: 'date',
            value: { dateStart: filters.dateStart, dateEnd: filters.dateEnd },
            isAiGenerated: true
        });
    }

    // Amount filter
    if (filters.amountMin !== undefined || filters.amountMax !== undefined) {
        rows.push({
            id: generateId(),
            type: 'amount',
            value: { min: filters.amountMin, max: filters.amountMax },
            isAiGenerated: true
        });
    }

    // Entity filter
    if (filters.ourEntity) {
        rows.push({
            id: generateId(),
            type: 'entity',
            value: filters.ourEntity,
            isAiGenerated: true
        });
    }

    // Category filter - create one row per level1 category
    if (filters.customerCategoryLevel1 && filters.customerCategoryLevel1.length > 0) {
        filters.customerCategoryLevel1.forEach(level1 => {
            rows.push({
                id: generateId(),
                type: 'category',
                value: {
                    level1,
                    level2: filters.customerCategoryLevel2 || []
                },
                isAiGenerated: true
            });
        });
    }

    return rows;
};

const FilterBar: React.FC<FilterBarProps> = ({
    categoryHierarchy,
    entityOptions,
    onFiltersChange,
    externalFilters
}) => {
    // Initialize with one empty row
    const [rows, setRows] = useState<FilterRowState[]>([
        { id: generateId(), type: null, value: null }
    ]);

    // Track previous externalFilters to detect changes
    const prevExternalFiltersRef = useRef<ExternalFilters | undefined>(undefined);

    // Sync external filters to internal rows when they change
    useEffect(() => {
        // Only process if externalFilters changed (not on initial mount with undefined)
        if (externalFilters && externalFilters !== prevExternalFiltersRef.current) {
            const hasFilters = Object.values(externalFilters).some(v =>
                v !== undefined && v !== null && (Array.isArray(v) ? v.length > 0 : true)
            );

            if (hasFilters) {
                const newRows = convertExternalFiltersToRows(externalFilters);
                // Merge with existing non-AI rows (preserve user's manual filters)
                setRows(prev => {
                    // Remove existing AI-generated rows
                    const manualRows = prev.filter(row => !row.isAiGenerated && row.type !== null);
                    // Combine: AI rows first, then manual rows, then empty row at end
                    const combined = [...newRows, ...manualRows];
                    // Ensure empty row at end
                    if (combined.length === 0 || combined[combined.length - 1].type !== null) {
                        combined.push({ id: generateId(), type: null, value: null });
                    }
                    return combined;
                });
            }
        }
        prevExternalFiltersRef.current = externalFilters;
    }, [externalFilters]);


    // Convert rows to filter parameters and notify parent
    const convertToFilters = useCallback((currentRows: FilterRowState[]) => {
        const filters: {
            dateStart?: string;
            dateEnd?: string;
            amountMin?: number;
            amountMax?: number;
            ourEntity?: string;
            customerCategoryLevel1?: string[];
            customerCategoryLevel2?: string[];
        } = {};

        currentRows.forEach(row => {
            if (!row.type || row.value === null) return;

            switch (row.type) {
                case 'date':
                    const dateValue = row.value as DateFilterValue;
                    if (dateValue.dateStart) filters.dateStart = dateValue.dateStart;
                    if (dateValue.dateEnd) filters.dateEnd = dateValue.dateEnd;
                    break;
                case 'amount':
                    const amountValue = row.value as AmountFilterValue;
                    if (amountValue.min !== undefined) filters.amountMin = amountValue.min;
                    if (amountValue.max !== undefined) filters.amountMax = amountValue.max;
                    break;
                case 'entity':
                    if (typeof row.value === 'string') filters.ourEntity = row.value;
                    break;
                case 'category':
                    const catValue = row.value as CategoryFilterValue;
                    if (catValue.level1) {
                        if (!filters.customerCategoryLevel1) {
                            filters.customerCategoryLevel1 = [];
                        }
                        if (!filters.customerCategoryLevel1.includes(catValue.level1)) {
                            filters.customerCategoryLevel1.push(catValue.level1);
                        }
                        // Only add level2 if specific selections are made (not empty = all)
                        if (catValue.level2 && catValue.level2.length > 0) {
                            if (!filters.customerCategoryLevel2) {
                                filters.customerCategoryLevel2 = [];
                            }
                            catValue.level2.forEach(l2 => {
                                if (!filters.customerCategoryLevel2!.includes(l2)) {
                                    filters.customerCategoryLevel2!.push(l2);
                                }
                            });
                        }
                    }
                    break;

            }
        });

        return filters;
    }, []);

    // Update parent when rows change
    useEffect(() => {
        const filters = convertToFilters(rows);
        onFiltersChange(filters);
    }, [rows, convertToFilters, onFiltersChange]);

    // Handle type change for a row
    const handleTypeChange = useCallback((id: string, type: FilterType | null) => {
        setRows(prev => {
            const newRows = prev.map(row => {
                if (row.id === id) {
                    // Reset value when type changes
                    let defaultValue: FilterValue = null;
                    if (type === 'date' || type === 'amount') {
                        defaultValue = {};
                    } else if (type === 'category') {
                        defaultValue = { level1: undefined, level2: [] };
                    }
                    return { ...row, type, value: defaultValue };
                }
                return row;
            });

            // If the modified row was the last empty row and now has a type,
            // add a new empty row at the bottom
            const lastRow = newRows[newRows.length - 1];
            if (lastRow && lastRow.type !== null) {
                newRows.push({ id: generateId(), type: null, value: null });
            }

            return newRows;
        });
    }, []);

    // Handle value change for a row
    // When user modifies a row, remove the AI-generated flag
    const handleValueChange = useCallback((id: string, value: FilterValue) => {
        setRows(prev => {
            const newRows = prev.map(row => {
                if (row.id === id) {
                    // Remove AI flag when user edits the value
                    return { ...row, value, isAiGenerated: false };
                }
                return row;
            });
            return newRows;
        });
    }, []);

    // Handle remove row
    const handleRemove = useCallback((id: string) => {
        setRows(prev => {
            // Don't remove if it's the only row
            if (prev.length === 1) {
                return [{ id: generateId(), type: null, value: null }];
            }

            const newRows = prev.filter(row => row.id !== id);

            // Ensure at least one empty row exists at the bottom
            const lastRow = newRows[newRows.length - 1];
            if (lastRow && lastRow.type !== null) {
                newRows.push({ id: generateId(), type: null, value: null });
            }

            return newRows;
        });
    }, []);

    // Handle clear all
    const handleClearAll = useCallback(() => {
        setRows([{ id: generateId(), type: null, value: null }]);
    }, []);

    // Get used filter types (to disable in other rows)
    // Note: 'category' type can be used multiple times to support multiple level1 selections
    const usedTypes = rows
        .filter(row => row.type !== null && row.type !== 'category')
        .map(row => row.type as FilterType);

    // Check if there are any active filters
    const hasActiveFilters = rows.some(row => row.type !== null);

    return (
        <div className="filter-bar">
            <div className="filter-bar-rows">
                {rows.map((row, index) => (
                    <FilterRow
                        key={row.id}
                        id={row.id}
                        type={row.type}
                        value={row.value}
                        onTypeChange={handleTypeChange}
                        onValueChange={handleValueChange}
                        onRemove={handleRemove}
                        usedTypes={usedTypes}
                        categoryHierarchy={categoryHierarchy}
                        entityOptions={entityOptions}
                        isLastRow={index === rows.length - 1 && row.type === null}
                        isAiGenerated={row.isAiGenerated}
                    />
                ))}
            </div>

            {hasActiveFilters && (
                <div className="filter-bar-footer">
                    <Button
                        type="text"
                        size="small"
                        icon={<CloseOutlined />}
                        onClick={handleClearAll}
                        className="clear-all-button"
                    >
                        清除筛选
                    </Button>
                </div>
            )}
        </div>
    );
};

export default FilterBar;
